"""Phase 3: Agent Brain - Main Orchestrator.

Orchestrates the entire RAG pipeline:
1. Query → Agentic Router → Decision (codebase, KT, both, or tool)
2. Retrieve from Phase 2 (using dynamic weights from Phase 2 optimization)
3. Select Few-Shot examples
4. Build prompt
5. Call LLM with streaming
6. Store in memory (PostgreSQL)
7. Return response to user

This is the "Brain" that ties everything together for intelligent response generation.
"""

import logging
from typing import AsyncIterator, Dict, Any, Optional, List
from dataclasses import dataclass
from datetime import datetime
import asyncio

# FIX #3: OpenTelemetry instrumentation
try:
    from opentelemetry import trace, metrics
    HAS_OTEL = True
    tracer = trace.get_tracer(__name__)
    meter = metrics.get_meter(__name__)
except ImportError:
    HAS_OTEL = False
    tracer = None
    meter = None

logger = logging.getLogger(__name__)


# Centralized debug logger — emits [ROUTER]/[RETRIEVER_START]/[RERANKER]/
# [PROMPT_BUILD]/[LLM_START]/[PARSER] tags so the operator can follow the
# full chat flow in the terminal.
from app.core.logger import logger as flow_logger, timed, log_step, log_success


# =============================================================================
# AUDIT FIX L2: Module-scope OTEL instrument declarations.
#
# Previously `meter.create_histogram(...)` was called *inside* the request
# handler on every query. That re-walked the meter's instrument registry,
# allocated a wrapper, and entered a lock per request — wasting CPU and
# risking duplicate instruments / double-counted metrics if the SDK's dedup
# semantics ever change.
#
# Instruments are now created exactly once at import time. `model` is added
# as an attribute on the per-record call so we can slice cost / latency by
# model in Grafana without label-exploding the metric name.
# =============================================================================
if HAS_OTEL and meter is not None:
    QUERY_LATENCY_MS = meter.create_histogram(
        name="agent_brain.query_latency_ms",
        description="Query processing latency (end-to-end)",
        unit="ms",
    )
    TOKENS_GENERATED = meter.create_histogram(
        name="agent_brain.tokens_generated",
        description="Tokens generated by LLM (sliced by model and kind)",
        unit="1",
    )
else:
    QUERY_LATENCY_MS = None
    TOKENS_GENERATED = None


@dataclass
class AgentConfig:
    """Configuration for the Agent Brain."""
    
    # LLM settings - read from environment for provider switching
    llm_model: str = None  # Will be set from .env via __post_init__
    llm_temperature: float = 0.7  # Creativity (0-1)
    llm_max_tokens: int = 2048  # Max response length
    llm_timeout_seconds: int = 60  # Timeout for LLM calls
    
    # Retrieval settings
    enable_retrieval: bool = True
    retrieve_k: int = 5  # Number of results
    use_dynamic_weights: bool = True  # Use Phase 2 optimization
    
    # Few-Shot settings
    enable_few_shot: bool = True
    num_examples: int = 2
    
    # Memory settings
    enable_memory: bool = True
    max_memory_tokens: int = 4096  # Summarize if longer
    memory_backend: str = "postgres"  # "postgres", "sqlite", "redis"
    
    # Tool invocation
    enable_tools: bool = True
    tools: List[str] = None  # ["code_search", "doc_search", "analyze"]
    
    # Streaming
    enable_streaming: bool = True
    stream_chunk_size: int = 100  # Characters per chunk
    
    def __post_init__(self):
        """Initialize configuration from environment variables."""
        import os
        
        # Load LLM model from environment based on provider
        if self.llm_model is None:
            llm_provider = os.getenv("LLM_PROVIDER", "groq").lower()
            
            if llm_provider == "groq":
                self.llm_model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
            elif llm_provider == "openai":
                self.llm_model = os.getenv("OPENAI_MODEL", "gpt-4o")
            elif llm_provider == "ollama":
                self.llm_model = os.getenv("OLLAMA_MODEL", "llama3.1")
            else:
                self.llm_model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        
        # Initialize tools list if not provided
        if self.tools is None:
            self.tools = ["code_search", "doc_search", "analyze"]


@dataclass
class AgentRequest:
    """Request to the agent."""
    
    query: str
    session_id: str
    user_id: str
    context: Optional[Dict[str, Any]] = None
    preferences: Optional[Dict[str, Any]] = None
    streaming: bool = True


@dataclass
class AgentResponse:
    """Response from the agent."""
    
    content: str
    session_id: str
    sources: List[Dict[str, Any]]  # Retrieved context
    reasoning: Dict[str, Any]  # Routing decision, etc.
    metadata: Dict[str, Any]  # Timing, tokens, etc.
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class AgentBrain:
    """Main orchestrator that ties together Phase 1, 2, and 3.
    
    Architecture:
    
    User Query
        ↓
    Agentic Router (Phase 3)
        ├─→ Routing Decision (codebase, KT, both, or tool)
        ↓
    Memory Manager
        └─→ Retrieve conversation history, summarize if needed
        ↓
    Phase 2 Retriever Engine
        ├─→ Dual-path search (vector + BM25)
        ├─→ Query expansion
        ├─→ Reranking
        └─→ Return: Top-5 results + parent context
        ↓
    Few-Shot Example Selector
        └─→ Find similar examples from knowledge base
        ↓
    Prompt Builder
        └─→ Build Few-Shot prompt with:
            ├─→ System instructions
            ├─→ Examples
            ├─→ Retrieved context
            └─→ User query
        ↓
    LLM (Llama 3.1)
        └─→ Generate response (streaming)
        ↓
    Memory Storage
        └─→ Store conversation in PostgreSQL
        ↓
    User
    """
    
    def __init__(
        self,
        config: Optional[AgentConfig] = None,
        retriever_engine=None,
        router=None,
        example_selector=None,
        prompt_builder=None,
        memory_manager=None,
        llm_client=None,
    ):
        """Initialize the Agent Brain.
        
        Args:
            config: AgentConfig
            retriever_engine: Phase 2 RetrieverEngine instance
            router: AgenticRouter instance
            example_selector: SemanticExampleSelector instance
            prompt_builder: FewShotPromptBuilder instance
            memory_manager: Chat memory manager
            llm_client: LLM client (e.g., Ollama, OpenAI, Groq)
        """
        self.config = config or AgentConfig()
        self.retriever = retriever_engine
        self.router = router
        self.example_selector = example_selector
        self.prompt_builder = prompt_builder
        self.memory_manager = memory_manager
        self.llm_client = llm_client
        
        # Metrics
        self.total_requests = 0
        self.total_tokens_generated = 0
        self.avg_latency_ms = 0.0
        
        logger.info("Initialized AgentBrain")
    
    async def process_query(
        self,
        request: AgentRequest,
    ) -> AgentResponse:
        """Process a user query end-to-end with robust error handling.
        
        Args:
            request: AgentRequest with user query and context
        
        Returns:
            AgentResponse with generated content
            
        ERROR HANDLING STRATEGY:
        - If retrieval fails: Use fallback (memory search)
        - If LLM fails: Use mock response
        - If memory fails: Still return response (with indication)
        - Always inform user of failures
        """
        # FIX #3: OpenTelemetry span for process_query
        if HAS_OTEL and tracer:
            with tracer.start_as_current_span("agent_brain.process_query") as span:
                span.set_attribute("query", request.query[:100])
                span.set_attribute("session_id", request.session_id)
                span.set_attribute("user_id", request.user_id)
                span.set_attribute("streaming", request.streaming)
                return await self._process_query_impl(request, span)
        else:
            return await self._process_query_impl(request, None)
    
    # ------------------------------------------------------------------ #
    # P2 #10: Unified core pipeline shared by streaming + non-streaming   #
    # ------------------------------------------------------------------ #
    async def _run_core_pipeline(
        self,
        request: AgentRequest,
        span: Optional[Any] = None,
    ) -> Dict[str, Any]:
        """Execute the entire pre-LLM pipeline once.

        Steps performed (identical for streaming and non-streaming callers):
            1. Load conversation history.
            2. Get intent analysis from Phase 2 retriever.
            3. Run AgenticRouter with intent + history.
            4. Retrieve context (Phase 2 hybrid + rerank + PDR + routing filter).
            5. Select few-shot examples.
            6. Build the structured-output prompt.

        Returns:
            Dict with keys: history, routing_result, sources, retrieval_metadata,
            examples, retrieved_context, prompt.

        The only thing this method DOES NOT do is invoke the LLM —
        that's the sole difference between streaming and non-streaming flows.
        """
        # Step 1
        history = await self._get_conversation_history(request.session_id)
        flow_logger.bind(tag="[HISTORY]").debug(
            f"loaded {len(history) if history else 0} prior message(s)"
        )

        # Step 2: Intent analysis (best-effort)
        intent_analysis = None
        try:
            if hasattr(self.retriever, "retrieve_with_intent"):
                with timed("[ROUTER] intent_analysis"):
                    _, intent_analysis = self.retriever.retrieve_with_intent(
                        query=request.query,
                        top_k=self.config.retrieve_k,
                    )
        except Exception as e:
            flow_logger.bind(tag="[ROUTER]").warning(f"intent analysis failed: {e}")

        # Step 3: Routing
        with timed("[ROUTER]") as r_ctx:
            routing_result = self.router.route(
                query=request.query,
                intent_analysis=intent_analysis,
                conversation_context=history,
            )
            r_ctx["decision"] = routing_result.decision.value
            r_ctx["conf"] = f"{routing_result.confidence:.2f}"
        if span:
            try:
                span.set_attribute("routing_decision", routing_result.decision.value)
                span.set_attribute("routing_confidence", routing_result.confidence)
                span.set_attribute(
                    "intent_type", routing_result.intent_type or "unknown"
                )
                span.set_attribute(
                    "intent_confidence", routing_result.intent_confidence
                )
            except Exception:
                pass

        # Step 4: Retrieval (with routing filter + dynamic weights)
        log_step(
            "[RETRIEVER_START]",
            f"hybrid search  k={self.config.retrieve_k}  decision={routing_result.decision.value}"
        )
        with timed("[RETRIEVER_START]") as ret_ctx:
            sources, retrieval_metadata = await self._retrieve_context(
                query=request.query,
                routing_decision=routing_result,
            )
            ret_ctx["sources"] = len(sources) if sources else 0
            ret_ctx["ok"] = retrieval_metadata.get("retrieval_success", False)

        # Reranker is invoked inside retriever_engine; emit a marker line so the
        # operator sees [RERANKER] in the trace even though the timing is
        # rolled into [RETRIEVER_START].
        if retrieval_metadata.get("reranked"):
            flow_logger.bind(tag="[RERANKER]").info(
                f"BGE-cross-encoder rescored {retrieval_metadata.get('candidates_before_rerank', '?')} "
                f"→ {len(sources)} top chunks"
            )
        if span:
            try:
                span.set_attribute(
                    "retrieval_success",
                    retrieval_metadata.get("retrieval_success", False),
                )
                span.set_attribute(
                    "sources_count", retrieval_metadata.get("sources_count", 0)
                )
            except Exception:
                pass

        # Step 5: Few-shot examples
        examples = None
        if self.config.enable_few_shot and self.example_selector:
            with timed("[PROMPT_BUILD] few_shot") as fs_ctx:
                examples = self.example_selector.select_examples(
                    query=request.query,
                    k=self.config.num_examples,
                )
                fs_ctx["k"] = len(examples) if examples else 0

        # Step 6: Build prompt
        retrieved_context = self._format_context(sources)
        if not retrieval_metadata.get("retrieval_success"):
            if retrieval_metadata.get("fallback_used"):
                retrieved_context += (
                    "\n\n[SYSTEM: Retrieval attempted with fallback. "
                    f"Status: {retrieval_metadata.get('fallback_used')}]"
                )
            else:
                retrieved_context += (
                    "\n\n[SYSTEM: No retrieval results available. "
                    f"Error: {retrieval_metadata.get('error', 'Unknown')}]"
                )

        with timed("[PROMPT_BUILD]") as pb_ctx:
            prompt = self.prompt_builder.build_prompt(
                user_query=request.query,
                retrieved_context=retrieved_context,
                num_examples=len(examples) if examples else 0,
            )
            pb_ctx["chunks"] = len(sources) if sources else 0
            pb_ctx["chars"] = len(prompt) if prompt else 0
        flow_logger.bind(tag="[PROMPT_BUILD]").debug(
            f"prompt_preview={prompt[:120].replace(chr(10), ' ')!r}…"
        )

        return {
            "history": history,
            "routing_result": routing_result,
            "sources": sources,
            "retrieval_metadata": retrieval_metadata,
            "examples": examples,
            "retrieved_context": retrieved_context,
            "prompt": prompt,
        }

    async def _process_query_impl(
        self,
        request: AgentRequest,
        span: Optional[Any] = None,
    ) -> AgentResponse:
        """Internal implementation of process_query (FIX #3)."""
        import time
        start_time = time.time()
        
        try:
            logger.info(f"Processing query: {request.query[:50]}...")

            # P2 #10: unified pre-LLM pipeline
            ctx = await self._run_core_pipeline(request, span)
            routing_result = ctx["routing_result"]
            sources = ctx["sources"]
            retrieval_metadata = ctx["retrieval_metadata"]
            examples = ctx["examples"]
            prompt = ctx["prompt"]

            # Step 6: Generate response (streaming if enabled)
            if request.streaming and self.config.enable_streaming:
                content, tokens = await self._generate_streaming_response(
                    prompt=prompt,
                    session_id=request.session_id,
                )
            else:
                content, tokens = await self._generate_response(prompt)
            
            # Step 7: Store in memory
            if self.config.enable_memory and self.memory_manager:
                try:
                    await self.memory_manager.add_message(
                        session_id=request.session_id,
                        user_id=request.user_id,
                        role="user",
                        content=request.query,
                    )
                    await self.memory_manager.add_message(
                        session_id=request.session_id,
                        user_id=request.user_id,
                        role="assistant",
                        content=content,
                    )
                except Exception as e:
                    logger.warning(f"Failed to store message in memory: {e}")
                    # Don't fail entire response if memory storage fails
            
            # Step 7.5: Parse structured output (PydanticOutputParser → AnswerSchema)
            # The prompt forces JSON-only output; here we tolerantly extract & validate.
            log_step("[PARSER]", "Attempting JSON → AnswerSchema parse")
            with timed("[PARSER]") as p_ctx:
                parsed_answer, parsed_sources, parsed_confidence = self._parse_structured_output(
                    content, fallback_sources=sources
                )
                p_ctx["ok"] = parsed_answer is not None
                p_ctx["confidence"] = (
                    f"{parsed_confidence:.2f}" if parsed_confidence is not None else "n/a"
                )
            if parsed_answer is None:
                flow_logger.bind(tag="[PARSER]").warning(
                    "structured parse failed — falling back to raw LLM text"
                )
            else:
                log_success(
                    "[PARSER]",
                    f"validated AnswerSchema  confidence={parsed_confidence}  "
                    f"reported_sources={len(parsed_sources) if parsed_sources else 0}"
                )
            # Replace raw content with the validated `answer` field for downstream UX.
            display_content = parsed_answer if parsed_answer else content

            # Step 8: Prepare response
            latency_ms = (time.time() - start_time) * 1000
            
            response = AgentResponse(
                content=display_content,
                session_id=request.session_id,
                sources=sources,
                reasoning=self._format_reasoning(routing_result),
                metadata={
                    "latency_ms": latency_ms,
                    "tokens_generated": tokens,
                    "tokens_per_second": tokens / (latency_ms / 1000),
                    "retrieval_decision": routing_result.decision.value,
                    "retrieval_confidence": routing_result.confidence,
                    "intent_type": routing_result.intent_type,  # FIX #2: Include intent
                    "intent_confidence": routing_result.intent_confidence,  # FIX #2: Include intent confidence
                    "examples_used": len(examples) if examples else 0,
                    # Structured-output validation
                    "structured_output_ok": parsed_answer is not None,
                    "llm_confidence_score": parsed_confidence,
                    "llm_reported_sources": parsed_sources,
                    # Add retrieval error info
                    "retrieval_success": retrieval_metadata.get("retrieval_success"),
                    "retrieval_error": retrieval_metadata.get("error"),
                    "fallback_used": retrieval_metadata.get("fallback_used"),
                    "retrieval_sources_count": retrieval_metadata.get("sources_count", 0),
                },
            )
            
            if span:
                span.set_attribute("tokens_generated", tokens)
                span.set_attribute("latency_ms", latency_ms)
            
            # Update metrics
            self.total_requests += 1
            self.total_tokens_generated += tokens
            self.avg_latency_ms = (
                (self.avg_latency_ms * (self.total_requests - 1) + latency_ms)
                / self.total_requests
            )
            
            # AUDIT FIX L2: record on the module-scope instruments declared
            # at import time. `model` and `kind` are passed as OTEL attributes
            # (Prometheus labels) — bounded set, safe for cardinality.
            if QUERY_LATENCY_MS is not None:
                model_name = getattr(self.config, "llm_model", "unknown")
                try:
                    QUERY_LATENCY_MS.record(
                        latency_ms,
                        attributes={"model": model_name},
                    )
                    TOKENS_GENERATED.record(
                        tokens,
                        attributes={"model": model_name, "kind": "output"},
                    )
                except Exception as e:
                    logger.debug(f"Failed to record metrics: {e}")
            
            log_msg = (
                f"Query processed in {latency_ms:.0f}ms, "
                f"generated {tokens} tokens, "
                f"retrieval: {'✓' if retrieval_metadata.get('retrieval_success') else '✗ (fallback)'}, "
                f"intent: {routing_result.intent_type or 'unknown'} ({routing_result.intent_confidence:.0%})"
            )
            logger.info(log_msg)
            
            return response
        
        except Exception as e:
            logger.error(f"Error processing query: {e}", exc_info=True)
            if span:
                span.record_exception(e)
                span.set_attribute("error", str(e))
            # Even on critical error, try to return something
            return AgentResponse(
                content=f"Error processing query: {str(e)}. Please try again.",
                session_id=request.session_id,
                sources=[],
                reasoning="Query processing failed",
                metadata={
                    "error": str(e),
                    "retrieval_success": False,
                },
            )
    
    async def process_query_streaming(
        self,
        request: AgentRequest,
    ) -> AsyncIterator[str]:
        """Process query with streaming response (with error handling).
        
        Yields chunks of response text as they're generated.
        
        ERROR HANDLING:
        - If retrieval fails: Uses fallback
        - If stream fails: Yields error message
        - Always attempts to provide response
        
        Args:
            request: AgentRequest
        
        Yields:
            Response chunks (including error messages if applicable)
        """
        try:
            # P2 #10: reuse the same retrieval+prompt pipeline as non-streaming.
            ctx = await self._run_core_pipeline(request, span=None)
            prompt = ctx["prompt"]

            # Step 6: Stream response with error handling
            chunk_count = 0
            full_response = ""
            try:
                async for chunk in self._stream_response(prompt):
                    full_response += chunk
                    yield chunk
                    chunk_count += 1
            except Exception as stream_error:
                logger.error(f"Stream interrupted: {stream_error}")
                yield f"\n\n[Stream interrupted: {str(stream_error)}]"
                return

            # Step 7: Store final response in memory (both sides for symmetry
            # with the non-streaming path).
            if self.config.enable_memory and self.memory_manager and chunk_count > 0:
                try:
                    await self.memory_manager.add_message(
                        session_id=request.session_id,
                        user_id=request.user_id,
                        role="user",
                        content=request.query,
                    )
                    if full_response:
                        await self.memory_manager.add_message(
                            session_id=request.session_id,
                            user_id=request.user_id,
                            role="assistant",
                            content=full_response,
                        )
                except Exception as mem_error:
                    logger.warning(f"Failed to store in memory: {mem_error}")
        
        except Exception as e:
            logger.error(f"Error in streaming: {e}", exc_info=True)
            error_msg = (
                f"\n\n[Error processing query: {str(e)}. "
                "Please try again or rephrase your question.]\n"
            )
            yield error_msg
    
    async def _retrieve_context(
        self,
        query: str,
        routing_decision,
    ) -> tuple[List[Dict[str, Any]], Dict[str, Any]]:
        """Retrieve context using Phase 2 retriever with error propagation & fallback.
        
        Returns:
            (sources, retrieval_metadata)
            - sources: List of retrieved contexts
            - retrieval_metadata: Info about retrieval (success, error, fallback used)
        
        FALLBACK STRATEGY:
        1. Try Phase 2 retriever (best)
        2. If fails: Try memory-based fallback (from conversation history)
        3. If fails: Return empty with error indication (LLM can still respond)
        """
        retrieval_metadata = {
            "retrieval_attempted": True,
            "retrieval_success": False,
            "fallback_used": None,
            "error": None,
            "sources_count": 0,
        }
        
        try:
            if not self.config.enable_retrieval or not self.retriever:
                error_msg = "Retrieval disabled or retriever not configured"
                logger.warning(error_msg)
                retrieval_metadata["error"] = error_msg
                retrieval_metadata["retrieval_attempted"] = False
                
                # Try memory fallback
                return await self._fallback_memory_search(query, retrieval_metadata)
            
            # P0 FIX #2: translate routing decision into a real Chroma filter
            metadata_filter = None
            try:
                from app.services.agents.agentic_router import (
                    routing_decision_to_metadata_filter,
                )
                metadata_filter = routing_decision_to_metadata_filter(routing_decision)
                if metadata_filter:
                    logger.info(
                        f"Applying routing metadata_filter={metadata_filter} "
                        f"(decision={routing_decision.decision.value})"
                    )
            except Exception as e:
                logger.debug(f"Could not derive metadata filter from routing: {e}")

            # P0 FIX #1: pass valid kwargs only — `use_dynamic_weights` is now
            # accepted by RetrieverEngine.retrieve() (was silently raising TypeError).
            retrieval = self.retriever.retrieve(
                query=query,
                top_k=self.config.retrieve_k,
                use_dynamic_weights=self.config.use_dynamic_weights,
                metadata_filter=metadata_filter,
            )

            # P1 FIX: RetrieverEngine returns a RetrievalResult dataclass, not a list.
            # Extract chunks; fall back gracefully if a list is returned (legacy path).
            if hasattr(retrieval, "chunks"):
                results = retrieval.chunks or []
                retrieval_metadata["retrieval_time_ms"] = getattr(
                    retrieval, "total_time_ms", 0.0
                )
                retrieval_metadata["candidates_before_rerank"] = getattr(
                    retrieval, "candidates_before_rerank", 0
                )
                retrieval_metadata["expanded_queries"] = getattr(
                    retrieval, "expanded_queries", [query]
                )
            else:
                results = retrieval or []

            if not results:
                logger.warning(f"No results from retriever for query: {query}")
                retrieval_metadata["error"] = "No results from retriever"
                
                # Try memory fallback
                return await self._fallback_memory_search(query, retrieval_metadata)
            
            # Convert to source format. RetrievalResult chunks may include
            # `parent_context` for full-context PDR injection into the prompt.
            sources = [
                {
                    "content": (r.get("parent_context") or r.get("content", "")),
                    "metadata": r.get("metadata", {}),
                    "score": r.get("score", 0.0),
                    "source": (r.get("metadata", {}) or {}).get(
                        "source", r.get("source", "unknown")
                    ),
                    "chunk_id": r.get("chunk_id", ""),
                    "parent_id": r.get("parent_id", ""),
                }
                for r in results
            ]
            
            retrieval_metadata["retrieval_success"] = True
            retrieval_metadata["sources_count"] = len(sources)
            logger.info(f"Retrieved {len(sources)} sources for query")
            
            return sources, retrieval_metadata
        
        except Exception as e:
            error_msg = f"Error retrieving context: {str(e)}"
            logger.error(error_msg, exc_info=True)
            retrieval_metadata["error"] = error_msg
            
            # Try memory fallback
            return await self._fallback_memory_search(query, retrieval_metadata)
    
    async def _fallback_memory_search(
        self,
        query: str,
        retrieval_metadata: Dict[str, Any],
    ) -> tuple[List[Dict[str, Any]], Dict[str, Any]]:
        """FALLBACK: Try to find relevant info from conversation memory.
        
        When retriever fails, search through conversation history for
        related discussions to provide context.
        """
        try:
            if not self.memory_manager:
                retrieval_metadata["fallback_used"] = "none"
                logger.warning("No memory manager for fallback")
                return [], retrieval_metadata
            
            # Search memory for related messages
            # (This would use semantic search on memory if available)
            logger.info("Attempting memory-based fallback retrieval")
            
            # For now: Return empty but mark fallback as attempted
            # In production: could search through memory with similarity
            retrieval_metadata["fallback_used"] = "memory_attempted"
            
            # Return empty sources but with fallback indication
            # LLM can still respond with explanation
            return [], retrieval_metadata
        
        except Exception as e:
            error_msg = f"Fallback memory search failed: {str(e)}"
            logger.error(error_msg, exc_info=True)
            retrieval_metadata["fallback_used"] = "memory_failed"
            retrieval_metadata["error"] = error_msg
            
            # Last resort: Return empty with error
            return [], retrieval_metadata
    
    async def _get_conversation_history(self, session_id: str) -> Optional[str]:
        """Get conversation history from memory."""
        try:
            if not self.config.enable_memory or not self.memory_manager:
                return None
            
            history = await self.memory_manager.get_history(
                session_id=session_id,
                max_tokens=self.config.max_memory_tokens,
            )
            
            return history
        
        except Exception as e:
            logger.error(f"Error getting history: {e}")
            return None
    
    
    async def _generate_response(self, prompt: str) -> tuple[str, int]:
        """Generate response from LLM.
        
        Supports multiple LLM backends via LangChain:
        - ChatOllama (local Llama 3.1 via Ollama)
        - ChatGroq (cloud Groq API)
        - ChatOpenAI (OpenAI GPT models)
        
        Falls back to mock if LLM not available.
        
        LLM Client Interface (required methods):
        - async generate(prompt, temperature, max_tokens, timeout) -> dict
          Returns: {"content": str, "tokens": int}
        - async stream(prompt, temperature, max_tokens) -> AsyncIterator[str]
          Yields: text chunks
        """
        try:
            if not self.llm_client:
                logger.warning("LLM client not configured, using mock response")
                return self._mock_response(prompt)
            
            log_step(
                "[LLM_START]",
                f"non-streaming  model={getattr(self.config, 'llm_model', '?')}  "
                f"temp={self.config.llm_temperature}  max_tokens={self.config.llm_max_tokens}"
            )
            with timed("[LLM_START]") as ll_ctx:
                # Call actual LLM via client
                response = await self.llm_client.generate(
                    prompt=prompt,
                    temperature=self.config.llm_temperature,
                    max_tokens=self.config.llm_max_tokens,
                    timeout=self.config.llm_timeout_seconds,
                )

                if isinstance(response, dict):
                    content, tokens = response.get("content", ""), response.get("tokens", 0)
                else:
                    # Direct string response
                    content, tokens = str(response), len(str(response).split()) // 4
                ll_ctx["tokens"] = tokens
                ll_ctx["chars"] = len(content)
            return content, tokens
        
        except Exception as e:
            flow_logger.bind(tag="[LLM_START]").error(f"FAILED: {e}")
            logger.error(f"Error generating response: {e}")
            return self._mock_response(prompt)
    
    def _mock_response(self, prompt: str) -> tuple[str, int]:
        """Return a mock response — gated by `settings.debug` (P2 #11).

        Production behavior: when `DEBUG=False` and no LLM client is
        configured, we surface a hard error instead of silently shipping a
        canned answer. The mock copy itself now lives in `mock_utils.py`.
        """
        try:
            from app.core.config import get_settings
            debug_enabled = bool(get_settings().debug)
        except Exception:
            debug_enabled = False

        if not debug_enabled:
            msg = (
                "LLM client is not configured and DEBUG mode is disabled. "
                "Refusing to return a mock response in production."
            )
            logger.error(msg)
            return msg, len(msg.split())

        from app.services.agents.mock_utils import get_mock_response
        logger.warning("Returning DEBUG mock response — do not ship this in prod.")
        return get_mock_response(prompt)
    
    async def _generate_streaming_response(
        self,
        prompt: str,
        session_id: str,
    ) -> tuple[str, int]:
        """Generate response with streaming."""
        full_response = ""
        token_count = 0
        
        try:
            async for chunk in self._stream_response(prompt):
                full_response += chunk
                token_count = len(full_response.split()) // 4  # Rough estimate
            
            return full_response, token_count
        
        except Exception as e:
            logger.error(f"Error streaming response: {e}")
            return full_response, token_count
    
    async def _stream_response(self, prompt: str) -> AsyncIterator[str]:
        """Stream response from LLM — supports LangChain and custom clients."""
        if not self.llm_client:
            yield "Error: LLM client not configured"
            return

        try:
            # ChatGroq uses model_name, not model
            model_name = getattr(self.llm_client, 'model_name', None) \
                or getattr(self.llm_client, 'model', None) \
                or getattr(self.config, 'llm_model', '?')
            log_step(
                "[LLM_START]",
                f"streaming  model={model_name}  "
                f"temp={self.config.llm_temperature}  "
                f"max_tokens={self.config.llm_max_tokens}  "
                f"prompt_chars={len(prompt)}"
            )
            chunk_count = 0

            # ── LangChain client (ChatGroq / ChatOpenAI / ChatOllama) ──
            if hasattr(self.llm_client, 'astream'):
                from langchain_core.messages import HumanMessage
                async for chunk in self.llm_client.astream(
                    [HumanMessage(content=prompt)]
                ):
                    if chunk.content:
                        chunk_count += 1
                        yield chunk.content

            # ── Custom client (.stream() interface) ──────────────────
            elif hasattr(self.llm_client, 'stream'):
                async for chunk in self.llm_client.stream(
                    prompt=prompt,
                    temperature=self.config.llm_temperature,
                    max_tokens=self.config.llm_max_tokens,
                ):
                    chunk_count += 1
                    yield chunk

            else:
                yield "Error: LLM client has no stream/astream method"
                return

            flow_logger.bind(tag="[LLM_START]").info(
                f"stream finished  chunks={chunk_count}"
            )

        except Exception as e:
            flow_logger.bind(tag="[LLM_START]").error(f"stream FAILED: {e}")
            logger.error(f"Error streaming: {e}")
            yield f"Error: {str(e)}"
    
    def _parse_structured_output(
        self,
        llm_text: str,
        fallback_sources: Optional[List[Dict[str, Any]]] = None,
    ) -> tuple:
        """Tolerantly parse the LLM's JSON output into AnswerSchema.

        Handles common LLM misbehaviors:
          - Conversational preamble before the JSON block
          - Markdown code-fences (```json ... ```)
          - Trailing prose after the JSON object

        Strategy:
          1. Try the strict PydanticOutputParser first.
          2. On failure, extract the first balanced {...} block via regex/braces
             and re-parse.
          3. On total failure, return (None, [], 0.0) — caller falls back to
             raw `llm_text`.

        Returns:
            (answer: str | None, sources: List[str], confidence_score: float)
        """
        from app.services.agents.few_shot_prompt import ANSWER_PARSER

        if not llm_text or ANSWER_PARSER is None:
            return None, [], 0.0

        # Attempt 1: strict parse
        try:
            parsed = ANSWER_PARSER.parse(llm_text)
            return parsed.answer, list(parsed.sources or []), float(parsed.confidence_score or 0.0)
        except Exception as e:
            logger.debug(f"Strict JSON parse failed, attempting tolerant extraction: {e}")

        # Attempt 2: extract first balanced JSON object
        import json as _json
        candidate = self._extract_json_block(llm_text)
        if candidate:
            try:
                parsed = ANSWER_PARSER.parse(candidate)
                return parsed.answer, list(parsed.sources or []), float(parsed.confidence_score or 0.0)
            except Exception:
                # Last-ditch: raw json.loads + manual coercion
                try:
                    obj = _json.loads(candidate)
                    return (
                        obj.get("answer"),
                        list(obj.get("sources") or []),
                        float(obj.get("confidence_score") or 0.0),
                    )
                except Exception as e:
                    logger.warning(f"Tolerant JSON parse failed: {e}")

        logger.warning(
            "LLM did not return valid JSON conforming to AnswerSchema; "
            "returning raw text. Consider OutputFixingParser for retry."
        )
        return None, [], 0.0

    @staticmethod
    def _extract_json_block(text: str) -> Optional[str]:
        """Return the first balanced top-level JSON object found in `text`."""
        if not text:
            return None
        # Strip common fences first
        cleaned = text.replace("```json", "```").strip()
        if "```" in cleaned:
            parts = cleaned.split("```")
            for p in parts:
                p = p.strip()
                if p.startswith("{") and p.endswith("}"):
                    return p
        # Brace-balance scan
        start = text.find("{")
        if start == -1:
            return None
        depth = 0
        in_str = False
        escape = False
        for i in range(start, len(text)):
            ch = text[i]
            if escape:
                escape = False
                continue
            if ch == "\\":
                escape = True
                continue
            if ch == '"':
                in_str = not in_str
                continue
            if in_str:
                continue
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return text[start : i + 1]
        return None

    @staticmethod
    def _safe_truncate(
        content: str,
        max_chars: int,
        marker: str = "\n... [truncated]",
    ) -> str:
        """G3 FIX — Boundary-aware truncation that does NOT corrupt LLM output.

        Two guarantees over a naive `content[:max_chars]`:
          1. Cut at the last newline within the budget when one exists nearby
             (avoids severing a statement / string / token mid-line, which
             confuses the LLM into continuing the partial code).
          2. Strip trailing backticks before appending the truncation marker —
             otherwise a cut landing inside a Markdown fence (` ``` `) would
             leave an unbalanced fence that bleeds the next prose paragraph
             into the prior code block in the rendered answer.
        """
        if len(content) <= max_chars:
            return content
        cut = content[:max_chars]
        # Prefer a newline boundary if one is reasonably close (within the
        # last ~500 chars of the budget). Otherwise honor the hard cap.
        last_nl = cut.rfind("\n")
        if last_nl > max_chars - 500:
            cut = cut[:last_nl]
        # Strip dangling backticks/whitespace that would unbalance fences.
        cut = cut.rstrip("`").rstrip()
        return cut + marker

    def _format_context(self, sources: List[Dict[str, Any]]) -> str:
        """Format retrieved sources for prompt injection.

        L3 FIX — Hard caps prevent LLM context-window overflow when PDR returns
        a massive parent (e.g. a 5000-line legacy function). Without these caps
        a single oversized parent can blow a 32k-token window.

        G3 FIX — Truncation is now boundary-aware via `_safe_truncate`, so cuts
        land at line breaks and never leave unbalanced ``` fences in the LLM
        prompt.
        """
        # ~4 chars/token. 8k chars ≈ 2k tokens per source; 24k chars ≈ 6k tokens total.
        MAX_CHARS_PER_SOURCE = 8000
        MAX_TOTAL_CHARS = 24000

        if not sources:
            fallback_message = (
                "📌 **Context Note**: I couldn't find specific information in the "
                "documentation or codebase for this query. However, I can provide you "
                "with general guidance and best practices based on common patterns "
                "and industry standards.\n\n"
                "**What you're getting**:\n"
                "✓ General best practices and principles\n"
                "✓ Common implementation patterns\n"
                "✓ Typical approaches to this problem\n\n"
                "**What you might want to do**:\n"
                "• Rephrase your question for better matches\n"
                "• Check the official documentation\n"
                "• Reference similar examples in the codebase\n\n"
            )
            return fallback_message

        formatted = "# Retrieved Code Context\n\n"
        total_chars = len(formatted)
        sources_included = 0
        sources_omitted = 0

        for i, source in enumerate(sources, 1):
            raw_content = source.get("content", "") or ""
            # G3 FIX — boundary-aware truncation (newline + fence-safe).
            content = self._safe_truncate(raw_content, MAX_CHARS_PER_SOURCE)

            block = (
                f"## Source {i}: {source.get('source', 'Unknown')}\n"
                f"(Relevance: {source.get('score', 0.0):.2%})\n\n"
                f"```\n{content}\n```\n\n"
            )

            # Total budget cap — stop adding sources rather than overflow.
            if total_chars + len(block) > MAX_TOTAL_CHARS:
                sources_omitted = len(sources) - i + 1
                break

            formatted += block
            total_chars += len(block)
            sources_included += 1

        if sources_omitted > 0:
            formatted += (
                f"_({sources_omitted} additional source"
                f"{'s' if sources_omitted != 1 else ''} omitted to fit the LLM "
                f"context window.)_\n"
            )

        logger.debug(
            f"_format_context: included {sources_included}/{len(sources)} sources "
            f"({total_chars} chars; cap {MAX_TOTAL_CHARS})"
        )
        return formatted
    
    def _format_reasoning(self, routing_result) -> Dict[str, Any]:
        """Format routing reasoning."""
        return {
            "decision": routing_result.decision.value,
            "priority": routing_result.priority.value,
            "sources": routing_result.sources_to_query,
            "reasoning": routing_result.reasoning,
            "confidence": routing_result.confidence,
            "tools": routing_result.recommended_tools,
        }
    
    def get_metrics(self) -> Dict[str, Any]:
        """Get agent metrics."""
        return {
            "total_requests": self.total_requests,
            "total_tokens": self.total_tokens_generated,
            "avg_latency_ms": self.avg_latency_ms,
            "tokens_per_request": (
                self.total_tokens_generated / self.total_requests
                if self.total_requests > 0
                else 0
            ),
        }
